"use client";
/* eslint-disable @next/next/no-img-element */
import { useEffect, useState } from 'react';
import { Download, FileArchive, RefreshCw, WandSparkles } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Choice, ErrorNote, FilePicker, FileQueue, joinFiles, saveBlob, TaskOutput, useTask } from './shared';
import { bytesLabel, extension, fileStem, qrPayload } from '@/lib/conversions';
import { binaryBlob, createZip, documentText, exportDocument, openZip, processPdf } from '@/lib/file-tools';
import type JSZip from 'jszip';

export function PdfPanel() {
  const [mode,setMode]=useState('merge');const [files,setFiles]=useState<File[]>([]);const [pages,setPages]=useState('');const [angle,setAngle]=useState('90');const task=useTask();
  const multi=mode==='merge'||mode==='images';
  const receive=(added:File[])=>{task.reset();try{if(added.some(f=>!(mode==='images'?/\.(png|jpe?g)$/i:/\.pdf$/i).test(f.name)))throw new Error(mode==='images'?'Choose JPG or PNG images.':'Choose PDF files.');setFiles(multi?joinFiles(files,added):added);}catch(e){task.setError((e as Error).message)}};
  return <Card className="panel"><div className="controls-grid"><Choice label="What would you like to do?" value={mode} onChange={v=>{setMode(v);setFiles([]);setPages('');task.reset()}} disabled={task.busy} options={[{value:'merge',label:'Merge PDFs'},{value:'extract',label:'Extract selected pages'},{value:'split',label:'Split pages into separate PDFs'},{value:'rotate',label:'Rotate pages'},{value:'images',label:'JPG / PNG to PDF'}]}/>{!multi&&<div className="field"><Label htmlFor="pdf-pages">Pages (optional)</Label><Input id="pdf-pages" value={pages} disabled={task.busy} placeholder="All pages, or 1, 3-5" onChange={e=>{setPages(e.target.value);task.reset()}} aria-describedby="pdf-range-help"/><small id="pdf-range-help">Page numbers start at 1. Leave empty for all pages.</small></div>}{mode==='rotate'&&<Choice label="Rotate clockwise" value={angle} onChange={v=>{setAngle(v);task.reset()}} disabled={task.busy} options={['90','180','270'].map(v=>({value:v,label:`${v}°`}))}/>}</div>
  <FilePicker title={mode==='images'?'Turn images into a PDF':'Choose your PDFs'} hint={mode==='images'?'JPG and PNG · one image per page':'PDF files without password protection'} accept={mode==='images'?'.jpg,.jpeg,.png':'.pdf'} multiple={multi} disabled={task.busy} onFiles={receive}/>
  <FileQueue files={files} onChange={f=>{setFiles(f);task.reset()}} disabled={task.busy} reorder={multi}/>
  <p className="help-note">{mode==='merge'?'Files are merged in the order shown. Use the arrows to reorder them.':mode==='images'?'Images are fitted to A4 pages while keeping their proportions.':mode==='split'?'Each selected page becomes its own PDF, packaged in one ZIP download.':'Your original file is kept. Download the new PDF below.'}</p>
  <div className="action-row"><Button variant="outline" disabled={task.busy||!files.length} onClick={()=>{setFiles([]);task.reset()}}>Clear files</Button><Button disabled={task.busy||!files.length||(mode==='merge'&&files.length<2)} onClick={()=>task.run(()=>processPdf(files,mode,pages,Number(angle)))}><WandSparkles/>{mode==='merge'?'Merge PDFs':mode==='images'?'Create PDF':mode==='split'?'Split PDF':mode==='rotate'?'Rotate PDF':'Extract pages'}</Button></div><TaskOutput task={task} label="Preparing your PDF…"/></Card>;
}

export function QrPanel() {
  const [kind,setKind]=useState('text');const [text,setText]=useState('');const [ssid,setSsid]=useState('');const [password,setPassword]=useState('');const [security,setSecurity]=useState('WPA');const [size,setSize]=useState('512');const [preview,setPreview]=useState('');const task=useTask();
  useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview)},[preview]);
  const reset=()=>{task.reset();setPreview('')};
  const generate=()=>task.run(async()=>{
    const payload=qrPayload(kind,text,ssid,password,security);if(new TextEncoder().encode(payload).length>1500)throw new Error('Use fewer than 1,500 bytes of text for a readable QR code.');
    const QR=(await import('qrcode')).default;const options={errorCorrectionLevel:'M' as const,margin:4,width:Number(size),color:{dark:'#111827',light:'#ffffff'}};
    const svg=await QR.toString(payload,{...options,type:'svg'});const dataUrl=await QR.toDataURL(payload,options);const png=await (await fetch(dataUrl)).blob();setPreview(URL.createObjectURL(png));
    return [{name:'qrcode.png',blob:png},{name:'qrcode.svg',blob:new Blob([svg],{type:'image/svg+xml'})}];
  });
  return <div className="two-column"><Card className="panel"><Choice label="QR code content" value={kind} onChange={v=>{setKind(v);reset()}} disabled={task.busy} options={[{value:'text',label:'Link or text'},{value:'wifi',label:'Wi-Fi network'}]}/>
  {kind==='text'?<div className="field"><Label htmlFor="qr-text">Link or text</Label><Textarea id="qr-text" value={text} disabled={task.busy} rows={5} placeholder="https://example.com" onChange={e=>{setText(e.target.value);reset()}}/></div>:<><div className="field"><Label htmlFor="qr-ssid">Network name (SSID)</Label><Input id="qr-ssid" value={ssid} disabled={task.busy} onChange={e=>{setSsid(e.target.value);reset()}}/></div><Choice label="Network security" value={security} disabled={task.busy} onChange={v=>{setSecurity(v);reset()}} options={[{value:'WPA',label:'WPA / WPA2 / WPA3'},{value:'WEP',label:'WEP'},{value:'nopass',label:'Open network'}]}/>{security!=='nopass'&&<div className="field"><Label htmlFor="qr-password">Wi-Fi password</Label><Input id="qr-password" type="password" autoComplete="off" value={password} disabled={task.busy} onChange={e=>{setPassword(e.target.value);reset()}}/></div>}<p className="help-note">Anyone who scans this code can join your network.</p></>}
  <Choice label="PNG resolution" value={size} disabled={task.busy} onChange={v=>{setSize(v);reset()}} options={['256','512','1024'].map(v=>({value:v,label:`${v} × ${v} pixels`}))}/><Button disabled={task.busy} onClick={generate}><WandSparkles/>Generate QR code</Button><TaskOutput task={task}/></Card>
  <Card className="panel qr-preview"><div>{preview?<img src={preview} alt="Generated QR code for the content you entered" width="300" height="300"/>:<div className="qr-empty"><FileArchive aria-hidden="true"/><p>Your QR code will appear here.</p></div>}</div><p>Download PNG for everyday use or SVG for printing at any size. Scan it once to check before sharing.</p></Card></div>;
}

export function ArchivePanel() {
  const [mode,setMode]=useState('create');const [files,setFiles]=useState<File[]>([]);const [zip,setZip]=useState<JSZip|null>(null);const [entries,setEntries]=useState<string[]>([]);const [opening,setOpening]=useState(false);const [extracting,setExtracting]=useState('');const task=useTask();
  const locked=opening||task.busy||!!extracting;
  const receive=async(added:File[])=>{task.reset();if(mode==='create'){try{setFiles(joinFiles(files,added,100))}catch(e){task.setError((e as Error).message)}return;}setZip(null);setEntries([]);setFiles(added);setOpening(true);try{const archive=await openZip(new Uint8Array(await added[0].arrayBuffer()));const names=Object.keys(archive.files).filter(n=>!archive.files[n].dir);if(!names.length)throw new Error('This ZIP contains no files.');setZip(archive);setEntries(names)}catch(e){task.setError((e as Error).message)}finally{setOpening(false)}};
  const extract=async(name:string)=>{setExtracting(name);task.setError('');try{const entry=zip?.file(name);if(!entry)throw new Error('The selected entry is missing.');saveBlob(binaryBlob(await entry.async('uint8array')),name.split('/').pop()||'file');}catch(e){task.setError((e as Error).message)}finally{setExtracting('')}};
  return <Card className="panel"><Choice label="Archive action" value={mode} disabled={locked} onChange={v=>{setMode(v);setFiles([]);setZip(null);setEntries([]);task.reset()}} options={[{value:'create',label:'Create a ZIP archive'},{value:'extract',label:'Open and extract a ZIP'}]}/><FilePicker title={mode==='create'?'Package your files together':'Open a ZIP archive'} hint={mode==='create'?'Any file type · up to 100 files / 100 MB combined':'Standard ZIP files · extracted size up to 128 MB'} accept={mode==='create'?'*':'.zip'} multiple={mode==='create'} disabled={locked} onFiles={receive}/><FileQueue files={files} onChange={f=>{setFiles(f);setZip(null);setEntries([]);task.reset()}} disabled={locked}/>
  {mode==='create'&&<div className="action-row"><span className="help-note">{files.length} files · {bytesLabel(files.reduce((n,f)=>n+f.size,0))}</span><Button disabled={!files.length||locked} onClick={()=>task.run(async()=>[{name:'archive.zip',blob:await createZip(files)}])}><FileArchive/>Create ZIP</Button></div>}
  {opening&&<p role="status">Opening archive…</p>}{entries.length>0&&<section className="archive-entries"><h3>{entries.length} files in this archive</h3><ul>{entries.map(name=><li key={name}><span>{name}</span><Button variant="outline" disabled={!!extracting} onClick={()=>extract(name)} aria-label={`Extract ${name}`}><Download/>{extracting===name?'Extracting…':'Extract'}</Button></li>)}</ul></section>}<TaskOutput task={task}/></Card>;
}

export function DocumentPanel() {
  const [files,setFiles]=useState<File[]>([]);const [text,setText]=useState('');const [format,setFormat]=useState('txt');const [reading,setReading]=useState(false);const task=useTask();
  const receive=async(added:File[])=>{task.reset();setText('');setFiles(added);setReading(true);try{if(!['docx','txt','html','htm'].includes(extension(added[0].name)))throw new Error('Choose a DOCX, TXT or HTML file.');const value=await documentText(added[0]);if(value.length>2e6)throw new Error('Use a document with fewer than 2 million text characters.');setText(value);if(!value.trim())throw new Error('No text found. Scanned documents and images are not supported.');}catch(e){task.setError((e as Error).message)}finally{setReading(false)}};
  return <Card className="panel"><p className="help-note">Convert the text in DOCX, TXT and HTML files. Original page layout, images and advanced formatting are not retained.</p><FilePicker hint="DOCX, TXT or HTML · or paste text below" accept=".docx,.txt,.html,.htm" disabled={reading||task.busy} onFiles={receive} maxMB={20}/><FileQueue files={files} disabled={reading||task.busy} onChange={f=>{setFiles(f);setText('');task.reset()}}/>{reading&&<p role="status">Reading document text…</p>}<div className="field"><Label htmlFor="doc-text">Document text (editable)</Label><Textarea id="doc-text" value={text} rows={9} disabled={task.busy||reading} onChange={e=>{setText(e.target.value);task.reset()}} placeholder="Or type / paste the document text here…"/></div><div className="action-row"><Choice label="Save text as" value={format} onChange={v=>{setFormat(v);task.reset()}} disabled={task.busy} options={[{value:'txt',label:'Plain text (.txt)'},{value:'docx',label:'Word document (.docx)'},{value:'html',label:'Web page (.html)'}]}/><Button disabled={task.busy||reading||!text.trim()} onClick={()=>task.run(async()=>[{name:`${files[0]?fileStem(files[0].name):'document'}.${format}`,blob:await exportDocument(text,format,files[0]?.name||'Document')}])}><WandSparkles/>Convert document</Button></div><TaskOutput task={task}/></Card>;
}
