"use client";
import { useRef, useState } from 'react';
import { ArrowLeftRight, Copy, Download, WandSparkles } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Choice, copyText, ErrorNote, FilePicker, saveBlob } from './shared';
import { readData, writeData, type DataFormat } from '@/lib/conversions';

export function DataPanel() {
  const [from,setFrom]=useState<DataFormat>('json');const [to,setTo]=useState<DataFormat>('csv');const [input,setInput]=useState('');const [output,setOutput]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [status,setStatus]=useState('');
  const formats=['json','csv','tsv','xml'].map(value=>({value,label:value.toUpperCase()}));
  const reset=()=>{setOutput('');setError('');setStatus('')};
  async function convert(){setBusy(true);reset();try{setOutput(await writeData(await readData(input,from),to));setStatus('Conversion complete. Your output is ready.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  const fileRef=useRef<HTMLInputElement>(null);
  const load=async(file:File)=>{reset();if(file.size>10*1024*1024){setError('Choose a data file smaller than 10 MB.');return;}const ext=file.name.split('.').pop()?.toLowerCase();if(!['json','csv','tsv','xml'].includes(ext||'')){setError('Choose a JSON, CSV, TSV or XML file.');return;}setBusy(true);try{setFrom(ext as DataFormat);setInput(await file.text())}catch{setError('Could not read that file.')}finally{setBusy(false)}};
  return <Card className="panel"><div className="format-toolbar"><Choice label="Input format" value={from} onChange={v=>{setFrom(v as DataFormat);reset()}} disabled={busy} options={formats}/><Button variant="outline" size="icon" aria-label="Swap input and output" disabled={busy||!output} onClick={()=>{setFrom(to);setTo(from);setInput(output);reset()}}><ArrowLeftRight/></Button><Choice label="Output format" value={to} onChange={v=>{setTo(v as DataFormat);reset()}} disabled={busy} options={formats}/></div>
  <div className="editor-grid"><div className="field"><div className="editor-heading"><Label htmlFor="data-input">Input</Label><div><input type="file" accept=".json,.csv,.tsv,.xml" hidden ref={fileRef} onChange={e=>{if(e.target.files?.[0])load(e.target.files[0]);e.target.value=''}}/><Button variant="ghost" disabled={busy} onClick={()=>fileRef.current?.click()}>Open file</Button><Button variant="ghost" disabled={busy} onClick={()=>{setFrom('json');setInput('[\n  { "name": "Mango", "price": 120 },\n  { "name": "Apple", "price": 180 }\n]');reset()}}>Example</Button></div></div><Textarea id="data-input" className="code-editor" value={input} disabled={busy} spellCheck={false} onChange={e=>{setInput(e.target.value);reset()}} placeholder="Paste data or open a file…"/></div><div className="field"><div className="editor-heading"><Label htmlFor="data-output">Output</Label><Button variant="ghost" disabled={!output} onClick={()=>copyText(output)}><Copy/>Copy</Button></div><Textarea id="data-output" className="code-editor" value={output} readOnly spellCheck={false} placeholder="Converted data appears here…"/></div></div>
  <p className="help-note">CSV / TSV use objects as rows and preserve text values. XML uses a data root on export and @_-prefixed keys for attributes.</p><ErrorNote error={error}/><p className="sr-only" role="status">{status}</p><div className="action-row"><Button variant="outline" disabled={busy||!input} onClick={()=>{setInput('');reset()}}>Clear</Button><div><Button variant="outline" disabled={!output} onClick={()=>saveBlob(new Blob([output],{type:'text/plain;charset=utf-8'}),`converted.${to}`)}><Download/>Download</Button><Button disabled={busy||!input.trim()} onClick={convert}><WandSparkles/>{busy?'Converting…':'Convert data'}</Button></div></div></Card>;
}

function encode64(text:string){const bytes=new TextEncoder().encode(text);let raw='';for(const b of bytes)raw+=String.fromCharCode(b);return btoa(raw)}
function decode64(text:string){const raw=atob(text.trim());return new TextDecoder('utf-8',{fatal:true}).decode(Uint8Array.from(raw,c=>c.charCodeAt(0)))}
const transforms:Record<string,(text:string)=>string>={
  'Base64 encode':encode64,'Base64 decode':decode64,'URL encode':encodeURIComponent,'URL decode':decodeURIComponent,
  'HTML escape':text=>text.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;'),
  'UPPERCASE':text=>text.toUpperCase(),'lowercase':text=>text.toLowerCase(),'Title Case':text=>text.toLowerCase().replace(/(^|\s)\S/g,c=>c.toUpperCase()),
  'Remove duplicate lines':text=>[...new Set(text.split(/\r?\n/))].join('\n'),'Sort lines A–Z':text=>text.split(/\r?\n/).sort((a,b)=>a.localeCompare(b)).join('\n'),
  'Trim line spaces':text=>text.split(/\r?\n/).map(x=>x.trim()).join('\n'),
};
export function TextPanel(){const [input,setInput]=useState('');const [output,setOutput]=useState('');const [action,setAction]=useState('Base64 encode');const [error,setError]=useState('');const reset=()=>{setOutput('');setError('')};
  return <Card className="panel"><Choice label="Text operation" value={action} onChange={v=>{setAction(v);reset()}} options={Object.keys(transforms)}/><div className="editor-grid"><div className="field"><Label htmlFor="text-input">Input text</Label><Textarea id="text-input" className="code-editor" value={input} onChange={e=>{setInput(e.target.value);reset()}} placeholder="Paste your text…"/></div><div className="field"><Label htmlFor="text-output">Result</Label><Textarea id="text-output" className="code-editor" value={output} readOnly placeholder="Transformed text appears here…"/></div></div><span className="help-note">{Array.from(input).length.toLocaleString()} characters · {input.trim()?input.trim().split(/\s+/).length.toLocaleString():0} words</span><ErrorNote error={error}/><div className="action-row"><Button variant="outline" onClick={()=>{setInput('');reset()}} disabled={!input}>Clear</Button><div><Button variant="outline" disabled={!output} onClick={()=>copyText(output)}><Copy/>Copy</Button><Button variant="outline" disabled={!output} onClick={()=>saveBlob(new Blob([output],{type:'text/plain;charset=utf-8'}),'converted.txt')}><Download/>Download</Button><Button disabled={!input} onClick={()=>{reset();try{if(input.length>2e6)throw new Error('Use fewer than 2 million characters.');setOutput(transforms[action](input))}catch(e){setError(e instanceof Error&&e.message.includes('million')?e.message:'The text is not valid for this operation. Check the encoding and try again.')}}}><WandSparkles/>Transform</Button></div></div><span className="sr-only" role="status">{output?'Text transformed. Result is ready.':''}</span></Card>}

export function InspectPanel(){const [details,setDetails]=useState<{name:string;size:string;mime:string;detected:string;modified:string;hash:string}|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  const inspect=async(files:File[])=>{setBusy(true);setDetails(null);setError('');try{const file=files[0];const bytes=new Uint8Array(await file.arrayBuffer());const header=Array.from(bytes.slice(0,12)).map(b=>String.fromCharCode(b)).join('');let detected='Unknown signature';if(bytes[0]===137&&header.slice(1,4)==='PNG')detected='PNG image';else if(bytes[0]===255&&bytes[1]===216)detected='JPEG image';else if(header.startsWith('GIF8'))detected='GIF image';else if(header.startsWith('%PDF'))detected='PDF document';else if(header.startsWith('PK\u0003\u0004'))detected='ZIP-based file (ZIP / DOCX / XLSX / PPTX)';else if(header.startsWith('RIFF'))detected=header.slice(8,12)==='WEBP'?'WebP image':header.slice(8,12)==='WAVE'?'WAV audio':'RIFF media';if(!crypto.subtle)throw new Error('File hashing requires a secure browser connection.');const digest=await crypto.subtle.digest('SHA-256',bytes);setDetails({name:file.name,size:`${file.size.toLocaleString()} bytes`,mime:file.type||'Not reported',detected,modified:new Date(file.lastModified).toLocaleString(),hash:Array.from(new Uint8Array(digest)).map(b=>b.toString(16).padStart(2,'0')).join('')})}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
  return <Card className="panel"><FilePicker hint="Any file type · metadata and SHA-256 fingerprint" accept="*" onFiles={inspect} disabled={busy} maxMB={64}/>{busy&&<p role="status">Calculating file fingerprint…</p>}<ErrorNote error={error}/>{details&&<><dl className="detail-grid">{[['File name',details.name],['Size',details.size],['Browser-reported type',details.mime],['Detected signature',details.detected],['Last modified',details.modified]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><div className="field"><Label htmlFor="file-hash">SHA-256 fingerprint</Label><Textarea id="file-hash" className="hash-output" value={details.hash} readOnly rows={2}/><Button variant="outline" onClick={()=>copyText(details.hash)}><Copy/>Copy fingerprint</Button></div></>}</Card>;
}
