"use client";
import { useState } from 'react';
import { Copy } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Choice, copyText, ErrorNote } from './shared';
import { baseNumber, convertUnit, unitGroups } from '@/lib/conversions';

export default function UtilityPanel(){const [group,setGroup]=useState('Length');const [from,setFrom]=useState('Metres (m)');const [to,setTo]=useState('Kilometres (km)');const [value,setValue]=useState('1000');let result='',error='';
  try{if(value.trim()){const n=convertUnit(Number(value),group,from,to);if(!Number.isFinite(n))throw new Error('The result is too large. Use a smaller number.');result=Number(n.toPrecision(12)).toString()}}catch(e){error=(e as Error).message}
  return <div className="utility-grid"><Card className="panel"><h2>Unit converter</h2><Choice label="Measurement" value={group} onChange={v=>{setGroup(v);const keys=Object.keys(unitGroups[v]);setFrom(keys[0]);setTo(keys[1])}} options={Object.keys(unitGroups)}/><div className="controls-grid"><div className="field"><Label htmlFor="unit-value">Value</Label><Input id="unit-value" type="number" value={value} onChange={e=>setValue(e.target.value)}/><Choice label="From unit" value={from} onChange={setFrom} options={Object.keys(unitGroups[group])}/></div><div className="field"><Label htmlFor="unit-result">Converted value</Label><Input id="unit-result" value={result} readOnly/><Choice label="To unit" value={to} onChange={setTo} options={Object.keys(unitGroups[group])}/></div></div><ErrorNote error={error}/><Button variant="outline" disabled={!result} onClick={()=>copyText(result)}><Copy/>Copy result</Button></Card><NumberPanel/><ColorPanel/></div>;
}
function NumberPanel(){const [value,setValue]=useState('255');const [radix,setRadix]=useState('10');let n:bigint|null=null,error='';try{if(value.trim())n=baseNumber(value,Number(radix))}catch(e){error=(e as Error).message}
  return <Card className="panel"><h2>Number bases</h2><Choice label="Input number base" value={radix} onChange={setRadix} options={[{value:'2',label:'Binary (base 2)'},{value:'8',label:'Octal (base 8)'},{value:'10',label:'Decimal (base 10)'},{value:'16',label:'Hexadecimal (base 16)'}]}/><div className="field"><Label htmlFor="base-input">Number</Label><Input id="base-input" value={value} onChange={e=>setValue(e.target.value)} spellCheck={false} autoComplete="off" aria-invalid={!!error}/></div><ErrorNote error={error}/><dl className="number-results">{[['Binary',2],['Octal',8],['Decimal',10],['Hex',16]].map(([label,base])=><div key={label}><dt>{label}</dt><dd><code>{n!==null?n.toString(Number(base)).toUpperCase():'—'}</code><Button size="icon" variant="ghost" aria-label={`Copy ${label} value`} disabled={n===null} onClick={()=>n!==null&&copyText(n.toString(Number(base)).toUpperCase())}><Copy/></Button></dd></div>)}</dl></Card>;
}
function parseColor(input:string):[number,number,number]|null {
  const value=input.trim();const hex=value.match(/^#?([\da-f]{3}|[\da-f]{6})$/i);if(hex){const s=hex[1].length===3?hex[1].split('').map(c=>c+c).join(''):hex[1];return [parseInt(s.slice(0,2),16),parseInt(s.slice(2,4),16),parseInt(s.slice(4,6),16)]}
  const rgb=value.match(/^rgb\(\s*(\d+(?:\.\d+)?)\s*[, ]\s*(\d+(?:\.\d+)?)\s*[, ]\s*(\d+(?:\.\d+)?)\s*\)$/i);if(rgb){const numbers=rgb.slice(1).map(Number);return numbers.every(n=>n>=0&&n<=255)?numbers.map(Math.round) as [number,number,number]:null}
  const hsl=value.match(/^hsl\(\s*(-?\d+(?:\.\d+)?)\s*[, ]\s*(\d+(?:\.\d+)?)%\s*[, ]\s*(\d+(?:\.\d+)?)%\s*\)$/i);if(hsl){let [h,s,l]=hsl.slice(1).map(Number);if(s>100||l>100)return null;h=((h%360)+360)%360;s/=100;l/=100;const a=s*Math.min(l,1-l);const f=(n:number)=>{const k=(n+h/30)%12;return Math.round(255*(l-a*Math.max(-1,Math.min(k-3,9-k,1))))};return [f(0),f(8),f(4)]}return null;
}
function ColorPanel(){const [value,setValue]=useState('#635bff');const color=parseColor(value);const rgb=color||[99,91,255];const hex='#'+rgb.map(v=>v.toString(16).padStart(2,'0')).join('');const [r,g,b]=rgb.map(v=>v/255);const max=Math.max(r,g,b),min=Math.min(r,g,b),d=max-min,l=(max+min)/2;let h=0;if(d){h=max===r?((g-b)/d+(g<b?6:0)):max===g?(b-r)/d+2:(r-g)/d+4;h*=60}const s=d?d/(1-Math.abs(2*l-1)):0;const values=[['HEX',hex.toUpperCase()],['RGB',`rgb(${rgb.join(', ')})`],['HSL',`hsl(${Math.round(h)}, ${Math.round(s*100)}%, ${Math.round(l*100)}%)`]];
  return <Card className="panel full-span"><h2>Colour formats</h2><div className="color-input"><input type="color" value={hex} aria-label="Choose a colour" onChange={e=>setValue(e.target.value)}/><div className="field"><Label htmlFor="color-value">HEX, RGB or HSL colour</Label><Input id="color-value" value={value} onChange={e=>setValue(e.target.value)} aria-describedby="color-help"/></div></div><p id="color-help" className="help-note">Examples: #635bff · rgb(99, 91, 255) · hsl(243, 100%, 68%)</p><ErrorNote error={!color?'Enter a valid HEX, RGB or HSL colour.':''}/><div className="color-results">{values.map(([label,text])=><div key={label}><span>{label}</span><code>{color?text:'—'}</code><Button variant="ghost" size="icon" aria-label={`Copy ${label} colour`} disabled={!color} onClick={()=>copyText(text)}><Copy/></Button></div>)}</div></Card>;
}
