"use client";
import { Component, lazy, Suspense, useEffect, useRef, useState, type ReactNode } from 'react';
import { Archive, Braces, CalendarClock, CheckCircle2, ChevronRight, CircleGauge, Code2, FileImage, FileSearch, FileText, Files, Info, Layers3, LockKeyhole, Music2, QrCode, Search, Type } from 'lucide-react';
import { Toaster } from 'sonner';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Busy } from '@/components/converter/shared';
import ImagePanel from '@/components/converter/image-panel';
const PdfPanel=lazy(()=>import('@/components/converter/file-panels').then(m=>({default:m.PdfPanel})));
const QrPanel=lazy(()=>import('@/components/converter/file-panels').then(m=>({default:m.QrPanel})));
const ArchivePanel=lazy(()=>import('@/components/converter/file-panels').then(m=>({default:m.ArchivePanel})));
const DocumentPanel=lazy(()=>import('@/components/converter/file-panels').then(m=>({default:m.DocumentPanel})));
const DataPanel=lazy(()=>import('@/components/converter/text-panels').then(m=>({default:m.DataPanel})));
const TextPanel=lazy(()=>import('@/components/converter/text-panels').then(m=>({default:m.TextPanel})));
const InspectPanel=lazy(()=>import('@/components/converter/text-panels').then(m=>({default:m.InspectPanel})));
const UtilityPanel=lazy(()=>import('@/components/converter/utility-panel'));
const MediaPanel=lazy(()=>import('@/components/converter/media-panel'));
const TimePanel=lazy(()=>import('@/components/converter/time-panel'));
const DeveloperPanel=lazy(()=>import('@/components/converter/developer-panel'));
const tools=[
  {id:'images',name:'Images',icon:FileImage,title:'Image converter',description:'Convert, resize and rotate images. Adjust quality and download a batch in one ZIP.',formats:'JPG · PNG · WebP',component:ImagePanel},
  {id:'pdf',name:'PDF tools',icon:Files,title:'PDF tools',description:'Merge files, extract or rotate pages, split a PDF, or turn images into a document.',formats:'PDF · JPG · PNG',component:PdfPanel,new:true},
  {id:'documents',name:'Documents',icon:FileText,title:'Document text converter',description:'Extract and edit document text, then save it in the format you need.',formats:'DOCX · TXT · HTML',component:DocumentPanel,new:true},
  {id:'media',name:'Audio & video',icon:Music2,title:'Audio & video converter',description:'Convert small media files, extract audio, or trim a clip. Processing stays on your device.',formats:'MP4 · WebM · MP3 · WAV · more',component:MediaPanel,new:true},
  {id:'archives',name:'ZIP archives',icon:Archive,title:'ZIP archive tools',description:'Package files together or open a ZIP and download individual files.',formats:'Create · Extract',component:ArchivePanel,new:true},
  {id:'qr',name:'QR codes',icon:QrCode,title:'QR code generator',description:'Create a QR code for a link, text or Wi-Fi network. Save it as PNG or SVG.',formats:'PNG · SVG',component:QrPanel,new:true},
  {id:'data',name:'Data',icon:Braces,title:'Data converter',description:'Move between structured formats with file import, copy and download.',formats:'JSON · CSV · TSV · XML',component:DataPanel},
  {id:'text',name:'Text',icon:Type,title:'Text tools',description:'Encode, decode and tidy up text with an instant, editable input.',formats:'Base64 · URL · Case · Lines',component:TextPanel},
  {id:'utilities',name:'Utilities',icon:CircleGauge,title:'Everyday converters',description:'Translate measurements, number bases and colour values.',formats:'Units · Numbers · Colours',component:UtilityPanel},
  {id:'inspect',name:'Inspect files',icon:FileSearch,title:'File inspector',description:'Read file details and generate a SHA-256 fingerprint to compare file contents.',formats:'Metadata · SHA-256',component:InspectPanel},
  {id:'time',name:'Date & time',icon:CalendarClock,title:'Date and timestamp converter',description:'Convert readable dates, ISO values and Unix timestamps into common time formats.',formats:'ISO 8601 · UTC · Unix',component:TimePanel,new:true},
  {id:'developer',name:'Developer',icon:Code2,title:'Developer tools',description:'Generate secure passwords, UUIDs and SHA-256 text fingerprints in your browser.',formats:'Passwords · UUID · SHA-256',component:DeveloperPanel,new:true},
];
const guides:Record<string,{steps:[string,string,string];notes:string[]}>= {
  images:{steps:['Choose one or more image files.','Select the output format, size, rotation and quality.','Convert, then download one file or the complete ZIP.'],notes:['Animated GIFs and animated images become a single still image.','PNG is lossless; the quality setting applies to JPG and WebP.']},
  pdf:{steps:['Choose the PDF action you need.','Add files and enter page numbers when the action asks for them.','Check the file order, convert and download the result.'],notes:['Password-protected PDFs are not supported.','For merging, arrange files with the arrow buttons before converting.']},
  documents:{steps:['Open a DOCX, TXT or HTML file, or paste text.','Review and edit the extracted text.','Choose TXT, DOCX or HTML and download the new document.'],notes:['This tool keeps readable text, not the original page layout or images.','Scanned documents need OCR and cannot be read here yet.']},
  media:{steps:['Choose a short audio or video file.','Select the output format and optional start time or duration.','Start conversion, wait for processing and download the result.'],notes:['The media engine is about 31 MB and loads only when conversion starts.','Keep clips small for faster conversion, especially on mobile devices.']},
  archives:{steps:['Choose whether to create or open a ZIP.','Add the files you want to package, or select one ZIP to inspect.','Create the archive or download the files you need.'],notes:['ZIP creation supports up to 100 files and 100 MB combined.','Encrypted, multipart and ZIP64 archives are not supported.']},
  qr:{steps:['Choose link/text or Wi-Fi content.','Enter the information and choose the PNG size.','Generate, scan once to verify, then download PNG or SVG.'],notes:['Anyone who scans a Wi-Fi QR code can see and use its connection details.','Use SVG for printing and PNG for messages or websites.']},
  data:{steps:['Choose the input and output formats.','Paste data or open a JSON, CSV, TSV or XML file.','Convert, review the output and copy or download it.'],notes:['CSV and TSV require a unique name for every column.','XML exports use a data root and row elements for table rows.']},
  text:{steps:['Choose the text operation.','Paste or type your input text.','Transform, review and copy or download the result.'],notes:['Base64 is an encoding format, not encryption.','The character and word counts update as you type.']},
  utilities:{steps:['Open the unit, number or colour section you need.','Enter a value and choose its source and target formats.','Copy the calculated result.'],notes:['Temperature conversion prevents values below absolute zero.','Number conversion supports exact integers with up to 1,024 digits.']},
  inspect:{steps:['Choose any file up to 64 MB.','Wait while the browser reads its metadata and fingerprint.','Copy the SHA-256 value to compare it with another source.'],notes:['Matching SHA-256 values strongly indicate that two files are identical.','The inspector reads the file locally and does not modify it.']},
  time:{steps:['Choose the date or timestamp input format.','Enter an ISO date or Unix timestamp.','Copy the ISO, UTC, local or Unix result you need.'],notes:['Dates without an explicit timezone use your device timezone.','Unix timestamps are shown in both seconds and milliseconds.']},
  developer:{steps:['Open the password, UUID or text fingerprint section.','Choose settings or enter the source text.','Generate and copy the result.'],notes:['Passwords and UUIDs use your browser’s secure random generator.','SHA-256 is one-way and is not encryption.']},
};
class ToolBoundary extends Component<{children:ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return{failed:true}}render(){return this.state.failed?<div className="panel" role="alert"><p>This tool could not load. Check your connection and reload the page.</p><Button onClick={()=>window.location.reload()}>Reload page</Button></div>:this.props.children}}

function ToolGuide({tool}:{tool:string}){const guide=guides[tool];return <section className="tool-guide" aria-labelledby={`guide-${tool}`}><div className="guide-heading"><span><Info aria-hidden="true"/></span><div><h2 id={`guide-${tool}`}>How to use this tool</h2><p>Complete these three steps. Your original file stays unchanged.</p></div></div><ol>{guide.steps.map((step,index)=><li key={step}><span>{index+1}</span><p>{step}</p></li>)}</ol><details><summary>Important notes</summary><ul>{guide.notes.map(note=><li key={note}><CheckCircle2 aria-hidden="true"/><span>{note}</span></li>)}</ul></details></section>}

export default function Home(){const [active,setActive]=useState('images');const [visited,setVisited]=useState(['images']);const [query,setQuery]=useState('');const main=useRef<HTMLElement>(null);const current=tools.find(t=>t.id===active)!;
  const select=(id:string)=>{setActive(id);setVisited(old=>old.includes(id)?old:[...old,id]);};
  useEffect(()=>{const requested=new URLSearchParams(window.location.search).get('tool');if(requested&&tools.some(tool=>tool.id===requested))select(requested)},[]);
  const filtered=tools.filter(t=>`${t.name} ${t.description} ${t.formats}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="app-shell"><a className="skip-link" href="#converter">Skip to converter</a><Toaster position="top-center" richColors/><header className="topbar"><a href="#" className="brand" onClick={()=>{select('images');setQuery('')}} aria-label="FormatFlow home"><span className="brand-mark"><Layers3 aria-hidden="true"/></span><strong>FormatFlow</strong><span className="version-label">v10</span></a><span className="privacy-chip"><LockKeyhole aria-hidden="true"/>Files stay on your device</span></header>
  <Tabs value={active} onValueChange={select} orientation="vertical" activationMode="manual" className="workspace"><aside className="sidebar" aria-label="Conversion tools"><div className="sidebar-heading"><span>YOUR TOOLBOX</span><strong>12 tools, one workspace</strong></div><div className="tool-search"><Search aria-hidden="true"/><Input aria-label="Find a conversion tool" placeholder="Find a tool…" value={query} onChange={e=>setQuery(e.target.value)}/></div><TabsList className="tool-nav" aria-label="Choose a converter">{tools.map(t=><TabsTrigger key={t.id} value={t.id} hidden={!filtered.includes(t)}><t.icon aria-hidden="true"/><span>{t.name}</span>{t.new&&<small>New</small>}<ChevronRight aria-hidden="true"/></TabsTrigger>)}</TabsList>{filtered.length===0&&<p className="no-tools" role="status">No matching tools. Try “PDF”, “audio” or “text”.</p>}<div className="local-note"><LockKeyhole aria-hidden="true"/><p><strong>Private by default</strong>Your files are processed in this browser and are never uploaded.</p></div></aside>
  <main id="converter" tabIndex={-1} ref={main} className="content"><div className="mobile-picker"><label id="mobile-tool-label">Choose a tool</label><Select value={active} onValueChange={select}><SelectTrigger aria-labelledby="mobile-tool-label"><SelectValue/></SelectTrigger><SelectContent>{tools.map(t=><SelectItem key={t.id} value={t.id}>{t.name}{t.new?' · New':''}</SelectItem>)}</SelectContent></Select></div><div className="page-head"><span className="eyebrow">{current.formats}</span><h1>{current.title}</h1><p>{current.description}</p></div><ToolGuide tool={active}/>
  {tools.map(t=><TabsContent key={t.id} value={t.id} forceMount hidden={active!==t.id} className="tool-content"><ToolBoundary><Suspense fallback={<Busy label="Loading this tool…"/>}>{visited.includes(t.id)&&<t.component/>}</Suspense></ToolBoundary></TabsContent>)}<nav className="seo-links" aria-label="Popular converter guides"><strong>Popular tools</strong><a href="/image-converter">Image converter</a><a href="/pdf-tools">PDF tools</a><a href="/json-to-csv">JSON to CSV</a><a href="/text-tools">Text tools</a><a href="/qr-code-generator">QR code generator</a><a href="/unit-converter">Unit converter</a><a href="/date-time-converter">Date & time</a><a href="/developer-tools">Developer tools</a></nav><footer><span>FormatFlow 10</span><p>Files are cleared when you close this page.</p><span>Choose → Convert → Download</span></footer></main></Tabs></div>;
}
